import os
import json
from groq import Groq
from dotenv import load_dotenv

from utils import compress_content, rate_limit_and_retry

# Load environment variables
load_dotenv()

@rate_limit_and_retry(max_retries=3, base_delay=2.0)
def summarize_article(title: str, content: str) -> str:
    """
    Summarizes a cybersecurity news article using the Groq API.
    """
    client = Groq()
    compressed = compress_content(content)
    
    prompt = f"""
    You are an expert cybersecurity analyst. Summarize the following news article into 3 to 5 concise bullet points.
    Focus specifically on capturing:
    - Vulnerability details
    - Attack impact
    - Affected systems
    - Mitigation
    
    Article Title: {title}
    Article Content: {compressed}
    
    Return ONLY the bullet points. Do not include introductory or concluding remarks.
    """
    
    response = client.chat.completions.create(
        messages=[
            {"role": "system", "content": "You are a helpful cybersecurity assistant."},
            {"role": "user", "content": prompt}
        ],
        model="llama-3.3-70b-versatile",
        temperature=0.3,
        max_tokens=500
    )
    return response.choices[0].message.content.strip()

@rate_limit_and_retry(max_retries=3, base_delay=2.0)
def generate_two_level_summary(title: str, content: str) -> dict:
    """
    Generates a TWO-LEVEL summary for important news:
    - SHORT SUMMARY (5-7 lines, email newsletter friendly)
    - DEEP SUMMARY (Detailed explanation: what, who, impact, mitigation, why)
    
    Returns a dictionary with 'short_summary' and 'deep_summary'.
    """
    client = Groq()
    compressed = compress_content(content)
    
    prompt = f"""
    You are an expert cybersecurity analyst tasked with translating complex threats into simple, easy-to-understand language.
    Read the following article and provide two distinct summaries written for a layman/general audience without overly technical jargon.
    
    1. [SHORT SUMMARY]: 3 to 5 lines summarizing the core issue simply.
    2. [DEEP SUMMARY]: A detailed breakdown explicitly covering:
       - What happened
       - Who is affected
       - Impact
       - Mitigation
       - Why it matters
       
    CRITICAL RULE: The ENTIRE Deep Summary MUST be a MINIMUM of 200 words. There is no maximum length limit. Be highly descriptive and accessible to non-technical readers.
       
    Format your response EXACTLY like this:
    [SHORT SUMMARY]
    (insert short summary text here)
    [DEEP SUMMARY]
    (insert deep summary text here)
    
    Article Title: {title}
    Article Content: {compressed}
    """
    
    response = client.chat.completions.create(
        messages=[
            {"role": "system", "content": "You are a professional cybersecurity technical writer."},
            {"role": "user", "content": prompt}
        ],
        model="llama-3.3-70b-versatile",
        temperature=0.2, # Extremely strict for predictable layout mapping
        max_tokens=1000
    )
    
    text = response.choices[0].message.content.strip()
    
    # Parse the two sections using basic string splitting
    short_summary = "Short summary generation failed."
    deep_summary = "Deep summary generation failed."
    
    try:
        if "[DEEP SUMMARY]" in text:
            parts = text.split("[DEEP SUMMARY]")
            deep_summary = parts[1].strip()
            
            short_part = parts[0].replace("[SHORT SUMMARY]", "").strip()
            short_summary = short_part
    except Exception as e:
        print(f"[Error] Parsing two-level summary failed: {e}")
        short_summary = text # Fallback: return everything in short
        
    return {
        "short_summary": short_summary,
        "deep_summary": deep_summary
    }

def summarize_from_json(json_input) -> list:
    """
    Takes JSON input (either string or parsed dict) generated by v2.py 
    and summarizes all news articles and CVEs inside it.
    """
    if isinstance(json_input, str):
        try:
            data = json.loads(json_input)
        except json.JSONDecodeError as e:
            print(f"[Error] Invalid JSON string: {e}")
            return []
    else:
        data = json_input
        
    results = []
    
    # Process news
    for article in data.get("news", []):
        title = article.get("title", "")
        content = article.get("content", "")
        if title and content:
            summary = summarize_article(title, content)
            results.append({"type": "news", "title": title, "summary": summary})
            
    # Process CVEs
    for cve in data.get("cves", []):
        cve_id = cve.get("cve_id", "")
        desc = cve.get("description", "")
        if cve_id and desc:
            title = f"Vulnerability: {cve_id}"
            summary = summarize_article(title, desc)
            results.append({"type": "cve", "title": title, "summary": summary})
            
    return results